# Generated by Django 5.1.2 on 2024-10-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='decsription',
            new_name='description',
        ),
    ]
