# Generated by Django 5.1.2 on 2024-10-17 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(2)])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(2)])),
                ('state', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(2)])),
                ('zipcode', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(2)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
    ]
