# Generated by Django 5.1.2 on 2024-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
